config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users
  #root 'users#index'
  get '/user_profile', to: 'users#user_profile'

  resources :books do
    resources :comments do
      resources :likes
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_one_attached :cover_image, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :book
	has_one :user, through: :book
	has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :book
	belongs_to :comment
	has_one :user, through: :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :comments, through: :books
  has_many :likes, through: :books
  has_one_attached :image, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {others: 0, author: 1}

  validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:role, :name, :contact, :image, :email, :password, :password_confirmation)
      end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:role, :name, :contact, :image, :email, :password, :current_password)
      end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :check_author, only: [:new, :create, :edit, :update, :destroy]
	before_action :my_book, only: [:show, :edit, :update, :destroy]

	def index
		@books = Book.all
	end

	def show
	end

	def new
		@book = Book.new
	end

	def create
		# byebug
		@book = current_user.books.new(book_params)
  
    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
	end

	def edit
	end

	def update
		if @book
			@book.update(book_params)
			redirect_to @book
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@book.destroy
		redirect_to root_path, status: :see_other
	end

	private

	def book_params
		params.require(:book).permit(:user_id, :title, :cover_image, :description)
	end

	def my_book
		@book = Book.find(params[:id])
	end

	def check_author
		render json: {errors: "you are not authorized to perform this action."} and return unless current_user.role == 'author'
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @book = Book.find(params[:book_id])
    @comment = @book.comments.create(comment_params)
    redirect_to book_path(@book)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
    @book = Book.find(params[:book_id])
    @like = @book.likes.create(like_params)
    redirect_to book_path(@book)
  end

  def like_on_comment
  	@comment = Comment.find(params[:comment_id])
  	@like = @comment.likes.create(like_params)
  	redirect_to book_comment_path(@comment)
  end

  private
    def like_params
      params.require(:like)#.permit(:book_id, :comment_id)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
	class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :my_user, only: [:show, :edit, :update]
	#before_action :check_user, only: [:create, :edit, :update, :destroy]

	def index
		@users = User.all
	end

	def show
	end

	def user_profile
		@current_userr = current_user
	end
=begin
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
	end
=end

	def edit
	end

	def update
		# byebug
		if @user
			@user.update(user_params)
      redirect_to user_profile_path
    else
      render :edit, status: :unprocessable_entity
    end
	end

	private

	def user_params
		params.require(:user).permit(:role, :name, :contact, :image, :email) 
	end

	def my_user
		@user = User.find(current_user.id)
	end

  #def check_user
	#	render json: {errors: "you are not authorized to perform this action."} and return unless current_user.role == 'author'
	#end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/turbo_devise_helper.rb
module TurboDeviseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_bookForm.html.erb
<%= form_with model: @book do |form| %>
  <% if @book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= form.text_field :title, class:"form-control", placeholder:"Book Title"  %>
  </div>
  <div class="form-group">
    <%= form.text_field :description, class:"form-control", placeholder:"Book Description" %>
  </div>
  <div class="form-group">
    <% if @book.cover_image.attached? %>
      <%= image_tag @book.cover_image, style: "width: 200px; display: block" %>
    <% end %>
    <%= form.file_field :cover_image, class:"form-control", placeholder:"Book Coverpage" %>
  </div>
  <div class="form-group">
    <%= form.submit :Submit, class:'btn btn-success' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render 'books/bookForm' %>
<%= link_to 'back to books', books_path, class:"btn btn-secondary" %>

app/views/books/index.html.erb
<h1>Book List :)</h1>
<% if current_user.role == 'author' %>
  <%= link_to 'Create Book', new_book_path, class:"btn btn-success" %>
<% end %>
<br/><br/>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Coverpage</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |bk| %>
    <tr>
      <td><%= bk.title%></td>
      <td><%= bk.description %></td>
      <td>
        <% if bk.cover_image.attached? %>
          <%= image_tag bk.cover_image, style: "width: 200px; display: block" %>
        <% end %>
        <%= bk.cover_image %>
      </td>
      <% if current_user.role == 'author' %>
        <td><%= link_to 'show', book_path(bk), class:"btn btn-secondary" %></td>
        <td><%= link_to 'edit', edit_book_path(bk), class:"btn btn-secondary" %></td>
        <td><%= link_to 'delete', bk, data: {turbo_method: :delete,turbo_confirm: "Are you sure?" },  class:"btn btn-danger" %>
        </td>
      <% else %>
        <td><%= link_to 'show', book_path(bk), class:"btn btn-secondary" %></td> 
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>Add Book</h1>
<%= render 'books/bookForm' %>
<%= link_to 'back to books', books_path, class:"btn btn-secondary" %>

app/views/books/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    Title: <%= @book.title %>
  </h1>
  <p class="lead">
    Description: <%= @book.description %> <br><br>
    <% if @book.cover_image.attached? %>
      <%= image_tag @book.cover_image, style: "width: 200px; display: block" %>
    <% end %>
    Coverpage: <%= @book.cover_image%> 
  </p>
</div>
<% if current_user.role == 'author' %>
  <%= link_to 'edit', edit_book_path(@book), class:"btn btn-secondary" %>
  <%= link_to 'back to books',  books_path, class:"btn btn-secondary" %>
  <%= link_to 'delete', @book, data: {turbo_method: :delete,turbo_confirm: "Are you sure?" }, class:"btn btn-danger" %>
<% else %>
  <%= link_to 'back to books',  books_path, class:"btn btn-secondary" %>
<% end %>


<h2>Comments</h2>
<%= render @book.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @book, @book.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Book App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
  </head>
  <body>
    <%= render 'users/header' %>
    <div class="container">
      <br/><br/>
      <% if notice%>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br/><br/>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Book App', books_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.role == 'author' %>
          <li class="nav-item">
            <%= link_to 'All Books', books_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'My Profile', user_profile_path(current_user.id), class: "nav-link"%>
          </li>
        <% else %>
        <li class="nav-item">
            <%= link_to 'All Books', books_path, class: "nav-link"%>
          </li>
        <li class="nav-item">
            <%= link_to 'My Profile', user_profile_path, class: "nav-link"%>
        </li>
        <% end %>
      <% else %>
      <% end %>
      <li class="nav-item">
            <%= link_to 'SignOut', destroy_user_session_path, data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?", class: "nav-link", class:"float-right" 
                      } %>           
      </li>
    </ul>
  </div>
</nav>

app/views/users/_userForm.html.erb
<%= form_with model: @user do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= form.text_field :name, class:"form-control", placeholder:"Name"  %>
  </div>
  <div class="form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
  <div class="form-group">
    <%= form.text_field :contact, class:"form-control", placeholder:"Contact" %>
  </div>
  <div class="form-group">
    <% if @user.image.attached? %>
      <%= image_tag @user.image, style: "width: 200px; display: block" %>
    <% end %>
    <%= form.file_field :image, class:"form-control", placeholder:"Avatar" %>
  </div>
  <div class="form-group">
    <%= form.submit :Submit, class:'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile!</h1>
<%= render 'users/userForm' %>
<%= link_to 'back to profile', user_profile_path, class:"btn btn-secondary" %>

app/views/users/index.html.erb
<% if current_user.role == 'author' %>
  <h1>User List :)</h1>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Contact</th>
        <th scope="col">User Role</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |usr| %>
      <tr>
        <td><%= usr.name %></td>
        <td><%= usr.email %></td>
        <td><%= usr.contact %></td>
        <td><%= usr.role %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <h2> Hello <%= @user.name %>!!</h2>
  </h1>
  <p class="lead">
    Your email: <%= @user.email %> <br>
    Your contact: <%= @user.contact %> <br>
    <% if @user.image.attached? %>
      <%= image_tag @user.image, style: "width: 200px; display: block" %>
    <% end %>
    Your image: <%= @user.image %> <br>
  </p>
</div>
<%= link_to 'edit', edit_user_path(@user), class:"btn btn-secondary" %>
<%= link_to 'back to profile', user_profile_path, class:"btn btn-secondary" %>

app/views/users/user_profile.html.erb
<h1>User Profile</h1>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Contact</th>
      <th scope="col">Image</th>
      <th scope="col">Your Role</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @current_userr.name %></td>
      <td><%= @current_userr.email %></td>
      <td><%= @current_userr.contact %></td>
      <td>
        <% if @current_userr.image.attached? %>
      <%= image_tag @current_userr.image, style: "width: 200px; display: block" %>
    <% end %>
        <%= @current_userr.image %>  
      </td>
      <td><%= @current_userr.role %></td>
     
      <td><%= link_to 'show', user_path(@current_userr), class:"btn btn-secondary" %></td>
      <td><%= link_to 'edit', edit_user_path(@current_userr), class:"btn btn-secondary" %></td>
    </tr>
  </tbody>
</table>